# 蓝牙信号强度相关
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# 配对蓝牙设备的最大数量最多5个
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5

# 是否开启蓝牙链接密码
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n

# 是否启用休眠
CONFIG_ZMK_SLEEP=y

# 进入空闲状态前的不活动毫秒数
CONFIG_ZMK_IDLE_TIMEOUT=300000
# 1800000 毫秒 = 30 分钟 * 60 秒 * 1000

# 增加键盘消抖
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=8
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=8

# 同时开启USB和BLE
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# 32kHz晶振启用开关
# CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
# CONFIG_CLOCK_CONTROL_NRF_K32SRC_30PPM=y

# 编码器开关n
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# RGB电源控制开关
CONFIG_ZMK_EXT_POWER=n

#启用RGB背光及灯效
CONFIG_WS2812_STRIP=n
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=90

CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=160
CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=20
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3
